name: CI-CD

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ master ]


jobs:

  test:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Build docker-compose stack
        run: docker-compose up -d --build

      - name: Check running containers
        run: docker ps -a

      - name: Check logs
        run: docker logs flask-tdd-docker_users_1

      - name: Run test suite
        run:  docker-compose exec -T users pytest "project/tests" -p no:warnings

      - name: Run flake8
        run: docker-compose exec -T users flake8 project

      - name: Run black
        run: docker-compose exec -T users black project --check


  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Login to Heroku Container Registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login

    - name: Build and push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web

    - name: Release
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web



